version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  data-volume:
    name: "data-volume"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
  spark-master:
    image: spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
  spark-worker-1:
    image: spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-2:
    image: spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-3:
    image: spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-4:
    image: spark-worker
    container_name: spark-worker-4
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8084:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-5:
    image: spark-worker
    container_name: spark-worker-5
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8085:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-6:
    image: spark-worker
    container_name: spark-worker-6
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8086:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-7:
    image: spark-worker
    container_name: spark-worker-7
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8087:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  spark-worker-6:
    image: spark-worker
    container_name: spark-worker-8
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8088:8081
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
    depends_on:
      - spark-master
  postgres-db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8090:8080
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
  #dbt-worker:
    #image: dbt-base
    #container_name: dbt-worker
    #ports:
      #- 80:80
    #volumes:
      #- shared-workspace:/opt/workspace
      #- data-volume:/datalake/source
  mysql-db:
    image: debezium/example-mysql:1.0
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    volumes:
      - shared-workspace:/opt/workspace
      - data-volume:/datalake/source
      - ./.data:/opt/workspace/data
      - ./.notebook:/opt/workspace/notebook
#networks:
  #default:
    #external:
      #name: postgres_default
